version: '3.8'

services:
  keycloak:
    build: .
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-network
    restart: unless-stopped

  # Optional: You can also use a PostgreSQL database for persistence in production environments
  # database:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak_user
  #     POSTGRES_PASSWORD: keycloak_password
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   networks:
  #     - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
  # pg_data:
  #   driver: local
